import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [data, setData] = useState({})

  useEffect(() => {
    async function fetchData() {
      const response = await fetch('api/itunes')
      const data = await response.json()
      setData(data.feed.entry)
    }
    fetchData()
  }, [])

  console.log('data', data);

  return (
    <>
      <Head>
        <title>Podcaster</title>
        <meta name="description" content="Generated by create next app by @jalofernandez" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <header className={styles.header}>
          <div className={styles.padds}>
            <h1 className={styles.title}>Podcaster</h1>
          </div>
        </header>

        <section className={`${styles.grid} ${styles.section}`}>
          {Array.isArray(data) && data.map((podcast) => (
            <article key={podcast.id.label} className={styles.article}>
              <picture className={styles.picture}>
                <img
                  className={styles.image}
                  src={podcast['im:image'][0].label}
                  alt={podcast['im:name'].label}
                  width={96}
                  height={96}
                />
              </picture>
              <div className={`${styles.card}`}>
                <h3 className={`${styles.name}`}>
                  {podcast['im:name'].label}
                </h3>
                <h5 className={`${styles.artist}`}>
                  {podcast['im:artist'].label}
                </h5>
              </div>
            </article>
          ))}
        </section>

        <footer className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={60}
            height={12}
            priority
          />
        </footer>
      </main>
    </>
  )
}
