import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import styles from '@/styles/Home.module.css'

import { useRouter } from 'next/router'

import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()

  const [data, setData] = useState({})

  useEffect(() => {
    async function fetchData() {
      const response = await fetch('api/itunes')
      const data = await response.json()
      setData(data.feed.entry)
    }
    fetchData()
  }, [])

  console.log('data', data);

  const mainTitle = 'Podcaster'

  return (
    <>
      <Head>
        <title>{mainTitle}</title>
        <meta name="description" content="Generated by create next app by @jalofernandez" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Header title={mainTitle} />

        <section className={`${styles.section} ${styles.animFadeInDown}`}>
          <ul className={styles.grid}>
            {Array.isArray(data) && data.map((podcast) => (
              <li
                key={podcast.id.label}
                className={styles.article}
                onClick={() => router.push(`/podcast/${encodeURIComponent(podcast.id.attributes['im:id'])}`)}
              >
                <picture className={styles.picture}>
                  <img
                    className={styles.image}
                    src={podcast['im:image'][0].label}
                    alt={podcast['im:name'].label}
                    width={96}
                    height={96}
                  />
                </picture>
                <div className={styles.card}>
                  <h3 className={styles.name}>
                    {podcast['im:name'].label}
                  </h3>
                  <h5 className={styles.artist}>
                    {podcast['im:artist'].label}
                  </h5>
                </div>
              </li>
            ))}
          </ul>
        </section>

        <footer className={`${styles.center} ${styles.animOpacity}`}>
          <Image
            className={styles.logo}
            src="/podcaster-main-logo.svg"
            alt="Podacaster Logotype"
            width={80}
            height={80}
            priority
          />
        </footer>
      </main>
    </>
  )
}
