import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] })

export default function PodcastPage() {
  const router = useRouter()
  const { id } = router.query

  const mainTitle = 'Podcaster'

  return (
    <>
      <Head>
        <title>{mainTitle}: {id}</title>
        <meta name="description" content="Generated by create next app by @jalofernandez" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <header className={styles.header}>
          <div>
            <h1 className={styles.title}>{mainTitle}</h1>
          </div>
        </header>
        <footer className={styles.center}>
          <Image
            className={styles.logo}
            src="/podcaster-main-logo.svg"
            alt="Podacaster Logotype"
            width={80}
            height={80}
            priority
          />
        </footer>
      </main>
    </>
  );
}
